mcpiper: add a missing include to fix build
Summary:
Without this the OSS build on Fedora fails:
```
AnsiColorCodeStream.cpp:69:10: error: no match for 'operator<<' (operand types
are 'std::ostream' {aka 'std::basic_ostream<char>'} and 'const char*')
```

Reviewed By: stuclar

Differential Revision: D25058784

fbshipit-source-id: 54bf3994f79f2902401f42764f03bda3daab4185